SELECT * FROM employee;
SELECT * FROM roomtype;
SELECT * FROM customer;
SELECT * FROM guest;
SELECT * FROM partner;
SELECT * FROM reservation;
SELECT * FROM room;
SELECT * FROM roomrate;
SELECT * FROM allocationexceptionreport;
